from __future__ import annotations

"""Gate task: F1 packaging smoke (static + shared installed-package proof).

Builds both configurations through the repository operator, installs the
relocatable package into two scratch prefixes with the pinned toolchain
CMake, then drives the EXTERNAL consumer project (outside the repository
build tree, under .generated-temp/f1-smoke/consumer-src — hand-authored
scratch, never generated by this script). The consumer imports the
installed package via find_package, links each variant, emits one event
per severity through the installed diag service, proves the one-writer
law (a second install() fails typed) and proves the shared DLL loads at
runtime. Finishes with a measured static-vs-shared emit overhead
comparison (Release).

Usage: f1_packaging_smoke.py [--skip-build] [--overhead N]
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from toolchain import validate

REPO_ROOT = Path(__file__).resolve().parent.parent
SCRATCH = REPO_ROOT / ".generated-temp" / "f1-smoke"
CONSUMER_SRC = SCRATCH / "consumer-src"
REPO_BUILD = REPO_ROOT / "build" / "vs2022-x64"

GENERATOR = "Visual Studio 17 2022"
ARCHITECTURE = "x64"
VSWHERE = Path(r"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe")

# (variant, link-shared?, consumer config, prefix it consumes from)
CONSUMER_MATRIX = (
    ("static", False, "Release", "release"),
    ("static", False, "Debug", "debug"),
    ("shared", True, "Release", "release"),
    ("shared", True, "Debug", "debug"),
)

OVERHEAD_LINE = re.compile(
    r"OVERHEAD n=(\d+) p50=([0-9.]+)ns p99=([0-9.]+)ns mean=([0-9.]+)ns")


def stage(message: str) -> None:
    print(f"[RUN ] f1-packaging-smoke: {message}", flush=True)


def ok(message: str) -> None:
    print(f"[ OK ] f1-packaging-smoke: {message}", flush=True)


def fail(stage_name: str, detail: str) -> None:
    print(f"[FAIL] f1-packaging-smoke: {stage_name}: {detail}", flush=True)
    raise SystemExit(1)


def run_checked(stage_name: str, command, timeout: int, cwd=None, env=None) -> str:
    """Runs a command with a bounded timeout; typed failure on any error."""
    printable = " ".join(str(part) for part in command)
    try:
        result = subprocess.run(
            [str(part) for part in command],
            cwd=str(cwd) if cwd else None,
            env=env,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            timeout=timeout,
            check=False,
        )
    except subprocess.TimeoutExpired:
        fail(stage_name, f"timeout after {timeout}s: {printable}")
    except OSError as exc:
        fail(stage_name, f"could not spawn {printable}: {exc}")
    if result.returncode != 0:
        tail = "\n".join((result.stdout or "").splitlines()[-40:])
        fail(stage_name, f"exit {result.returncode}: {printable}\n{tail}")
    return result.stdout or ""


def operator_run(task: str, timeout: int) -> None:
    """All in-repo builds/configures go through the repo operator only."""
    env = os.environ.copy()
    env["MSBUILDDISABLENODEREUSE"] = "1"
    run_checked(f"operator {task}",
                ["cmd", "/c", REPO_ROOT / "tools" / "qiven.cmd", "run", task],
                timeout=timeout, cwd=REPO_ROOT, env=env)


def find_dumpbin():
    """Locates dumpbin (vswhere first, PATH second) for the import-table proof."""
    found = shutil.which("dumpbin")
    if found:
        return Path(found)
    if VSWHERE.is_file():
        try:
            result = subprocess.run(
                [str(VSWHERE), "-latest", "-products", "*",
                 "-requires", "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
                 "-property", "installationPath"],
                text=True, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL,
                timeout=60, check=False)
        except (OSError, subprocess.TimeoutExpired):
            return None
        root = (result.stdout or "").strip()
        if root:
            matches = sorted(Path(root).glob("VC/Tools/MSVC/*/bin/Hostx64/x64/dumpbin.exe"))
            if matches:
                return matches[-1]
    return None


def assert_package_layout(prefix: Path, config: str) -> None:
    """The relocatable tree must contain the full package, both variants."""
    expected = [
        "lib/cmake/qiven-foundation/qiven-foundationConfig.cmake",
        "lib/cmake/qiven-foundation/qiven-foundationConfigVersion.cmake",
        "lib/cmake/qiven-foundation/qiven-foundation-targets.cmake",
        "include/qiven/diag/service.hpp",
        "include/qiven/diag/event.hpp",
        "include/qiven/diag/ring.hpp",
        "include/qiven/foundation_export.hpp",
        "lib/qiven-foundation.lib",
        "lib/qiven-foundation-shared.lib",
        "bin/qiven-foundation-shared.dll",
    ]
    for relative in expected:
        if not (prefix / relative).is_file():
            fail(f"install-{config}", f"missing installed artifact: {prefix / relative}")
    ok(f"install-{config}: package layout complete at {prefix}")


def run_consumer(cmake: str, variant: str, link_shared: bool, config: str,
                 prefix_key: str, prefixes: dict, dumpbin) -> None:
    name = f"{variant}-{config.lower()}"
    prefix = prefixes[prefix_key]
    build_dir = SCRATCH / "consumer-build" / name
    shutil.rmtree(build_dir, ignore_errors=True)

    stage(f"consumer {name}: configure (external project, pinned cmake)")
    run_checked(
        f"consumer {name}",
        [cmake, "-S", CONSUMER_SRC, "-B", build_dir, "-G", GENERATOR, "-A", ARCHITECTURE,
         f"-Dqiven-foundation_DIR={prefix / 'lib' / 'cmake' / 'qiven-foundation'}",
         f"-DQIVEN_CONSUMER_LINK_SHARED={'ON' if link_shared else 'OFF'}"],
        timeout=300)

    stage(f"consumer {name}: build {config}")
    env = os.environ.copy()
    env["MSBUILDDISABLENODEREUSE"] = "1"
    run_checked(f"consumer {name}",
                [cmake, "--build", build_dir, "--config", config, "--parallel"],
                timeout=900, env=env)

    exe = build_dir / config / "f1-consumer.exe"
    if not exe.is_file():
        fail(f"consumer {name}", f"consumer executable missing: {exe}")

    run_dir = SCRATCH / "runs" / name
    shutil.rmtree(run_dir, ignore_errors=True)
    run_dir.mkdir(parents=True)
    sink = run_dir / "diag.log"
    marker = run_dir / "marker.txt"

    # loader resolution: the shared DLL is found through the installed
    # package's bin directory (never a copy into the build tree)
    run_env = os.environ.copy()
    run_env["PATH"] = str(prefix / "bin") + os.pathsep + run_env.get("PATH", "")

    loader_proof = ""
    if link_shared and dumpbin is None:
        # dumpbin unavailable: fallback proof — the DLL beside the exe
        # (loader resolves it there) and the marker written by a run that
        # emitted THROUGH the DLL
        shutil.copy2(prefix / "bin" / "qiven-foundation-shared.dll", exe.parent)
        loader_proof = "dll-beside-exe + run marker (dumpbin unavailable)"

    stage(f"consumer {name}: run (emit through the installed package)")
    run_checked(f"consumer {name}", [exe, sink, marker], timeout=180, cwd=run_dir,
                env=run_env)

    if not marker.is_file() or "ok=1" not in marker.read_text(encoding="ascii"):
        fail(f"consumer {name}", f"run marker missing/inconclusive: {marker}")
    if not sink.is_file() or sink.stat().st_size == 0:
        fail(f"consumer {name}", f"sink file missing/empty: {sink}")

    if link_shared:
        if dumpbin is not None:
            imports = run_checked(f"consumer {name}", [dumpbin, "/imports", exe],
                                  timeout=120)
            if "qiven-foundation-shared.dll" not in imports:
                fail(f"consumer {name}",
                     "import table does not reference qiven-foundation-shared.dll")
            loader_proof = "dumpbin import table + loader resolution from installed bin"
        elif not (exe.parent / "qiven-foundation-shared.dll").is_file():
            fail(f"consumer {name}", "fallback loader proof DLL not beside the exe")
    ok(f"consumer {name}: emit/one-writer/shutdown proven through the installed package"
       + (f" [{loader_proof}]" if loader_proof else ""))


def run_overhead(cmake: str, variant: str, link_shared: bool, config: str,
                 prefix_key: str, prefixes: dict, count: int) -> dict:
    name = f"{variant}-{config.lower()}"
    build_dir = SCRATCH / "consumer-build" / name
    exe = build_dir / config / "f1-consumer.exe"
    run_dir = SCRATCH / "runs" / f"{name}-overhead"
    shutil.rmtree(run_dir, ignore_errors=True)
    run_dir.mkdir(parents=True)

    stage(f"overhead {name}: {count} timed emits")
    run_env = os.environ.copy()
    run_env["PATH"] = str(prefixes[prefix_key] / "bin") + os.pathsep \
        + run_env.get("PATH", "")
    output = run_checked(f"overhead {name}",
                         [exe, "--overhead", count, run_dir / "sink.log",
                          run_dir / "marker.txt"],
                         timeout=600, cwd=run_dir, env=run_env)
    match = OVERHEAD_LINE.search(output)
    if match is None:
        fail(f"overhead {name}", f"no OVERHEAD line in consumer output:\n{output[-400:]}")
    values = {
        "n": int(match.group(1)),
        "p50": float(match.group(2)),
        "p99": float(match.group(3)),
        "mean": float(match.group(4)),
    }
    ok(f"overhead {name}: n={values['n']} p50={values['p50']:.1f}ns "
       f"p99={values['p99']:.1f}ns mean={values['mean']:.1f}ns")
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description="F1 packaging smoke gate task")
    parser.add_argument("--skip-build", action="store_true",
                        help="skip the operator build stage (tree already built)")
    parser.add_argument("--overhead", type=int, default=200000, metavar="N",
                        help="emit count for the overhead comparison (default 200000)")
    args = parser.parse_args()

    tools = validate()  # typed SystemExit on toolchain mismatch
    ok(f"toolchain pinned (cmake {tools['cmake_version']})")

    if not (CONSUMER_SRC / "CMakeLists.txt").is_file() \
            or not (CONSUMER_SRC / "main.cpp").is_file():
        fail("consumer", f"external consumer project missing under {CONSUMER_SRC} "
                         "(scratch, hand-authored; it is never generated)")

    if args.skip_build:
        ok("build stage skipped (--skip-build)")
    else:
        stage("operator configure")
        operator_run("configure", timeout=900)
        ok("operator configure")
        for task in ("build-release", "build-debug"):
            stage(f"operator {task}")
            operator_run(task, timeout=2400)
            ok(f"operator {task}")

    cmake = tools["cmake"]
    prefixes: dict = {}
    for config in ("release", "debug"):
        prefix = SCRATCH / f"install-{config}"
        shutil.rmtree(prefix, ignore_errors=True)
        stage(f"cmake --install {config} -> {prefix}")
        run_checked(f"install-{config}",
                    [cmake, "--install", REPO_BUILD, "--config", config.capitalize(),
                     "--prefix", prefix],
                    timeout=300)
        assert_package_layout(prefix, config)
        prefixes[config] = prefix
    ok("install: relocatable package installed for both configurations")

    dumpbin = find_dumpbin()
    if dumpbin is not None:
        ok(f"loader proof tool: dumpbin ({dumpbin})")
    else:
        ok("loader proof tool: dumpbin NOT found; using dll-beside-exe + marker fallback")

    for variant, link_shared, config, prefix_key in CONSUMER_MATRIX:
        run_consumer(cmake, variant, link_shared, config, prefix_key, prefixes, dumpbin)

    static_values = run_overhead(cmake, "static", False, "Release", "release",
                                 prefixes, args.overhead)
    shared_values = run_overhead(cmake, "shared", True, "Release", "release",
                                 prefixes, args.overhead)
    ok(f"overhead comparison (Release, n={args.overhead}): "
       f"static p50={static_values['p50']:.1f}ns mean={static_values['mean']:.1f}ns | "
       f"shared p50={shared_values['p50']:.1f}ns mean={shared_values['mean']:.1f}ns | "
       f"ratio shared/static p50={shared_values['p50'] / static_values['p50']:.2f}x "
       f"mean={shared_values['mean'] / static_values['mean']:.2f}x")

    ok("all stages green")
    return 0


if __name__ == "__main__":
    sys.exit(main())
